profiles:
  ustc:
    dataset_name: USTC-TFC2016
    dataset_type: ustc_flat
    source_dir: SourceData/USTC-TFC2016
    train_ratio: 0.8
    seed: 42
    allow_session_split_fallback: true
    byte_mode: payload
    merge_bidirectional: true
    sanitize_headers: true
    min_chunk_bytes: 1
    min_session_bytes: 1
    target_length: 784
    image_size: 28

  cic5_payload:
    dataset_name: CIC5_payload
    dataset_type: cic_hierarchical
    source_dir: SourceData/CICAndMal2017
    include_majors:
      - Adware
      - Benign
      - Ransomware
      - SMSMalware
      - Scareware
    label_map:
      sms-malware: SMSMalware
      sms_malware: SMSMalware
      smsmalware: SMSMalware
    train_ratio: 0.8
    seed: 42
    byte_mode: payload
    merge_bidirectional: true
    sanitize_headers: true
    min_chunk_bytes: 1
    min_session_bytes: 1
    target_length: 784
    image_size: 28

  cic5_fullpacket:
    dataset_name: CIC5_fullpacket
    dataset_type: cic_hierarchical
    source_dir: SourceData/CICAndMal2017
    include_majors:
      - Adware
      - Benign
      - Ransomware
      - SMSMalware
      - Scareware
    label_map:
      sms-malware: SMSMalware
      sms_malware: SMSMalware
      smsmalware: SMSMalware
    train_ratio: 0.8
    seed: 42
    byte_mode: full_packet
    merge_bidirectional: true
    sanitize_headers: true
    min_chunk_bytes: 1
    min_session_bytes: 1
    target_length: 784
    image_size: 28
